import './stylesheets/styles.scss'
import COLORS from './data/colors'
import './helpers/color_helpers'
import './event_listeners/color_listeners'
import './requests/color_requests'
import './prototypes/prototype'
